version: 0.2

env:
  variables:
    CACHE_CONTROL: "100"
    S3_BUCKET: dev-artifacts-114838604208
    FOLDER: deploys/project

phases:

  install:
    runtime-versions:
      python: 3.9

  build:
    commands:
      - echo Entered the build phase...
      - aws cloudformation deploy --template-file ./templates/pipeline.yaml --stack-name dev-deploy-pipeline --parameter-overrides BucketArtifactName=dev-artifacts-114838604208 --capabilities CAPABILITY_AUTO_EXPAND CAPABILITY_NAMED_IAM CAPABILITY_IAM --no-fail-on-empty-changeset

  post_build:
    commands:
      - cd src/layers/python
      - pip install --target . -r requirements.txt
      - cd..
      - zip -r dependencies.zip ./python
      - aws s3 cp dependencies.zip s3://${S3_BUCKET}/${FOLDER}/dependencies.zip
      - cd..
      - cd..
      - | 
        for t in $(ls "templates");
          do
            aws cloudformation package --template-file ./templates/$t --s3-bucket ${S3_BUCKET} --output-template-file ./templates/$t --s3-prefix ${FOLDER}
            if [ "${t}" != "MasterTemplate.json" ]
            then
              aws s3 cp ./templates/$t s3://${S3_BUCKET}/${FOLDER}/$t
            fi
          done
      - cd templates
      - zip -r MasterTemplate.zip ./MasterTemplate.json
      - aws s3 cp MasterTemplate.zip s3://${S3_BUCKET}/${FOLDER}/MasterTemplate.zip

artifacts:
   files:
     - '**/*'
