Description: Configure associations to allow access to resource.

Parameters:
  Name:
    Type: String
    Description: An environment name that will be prefixed to resource names

  VPCID:
    Type: AWS::EC2::VPC::Id
    Description: Choose which VPC the security groups should be deployed to

  PrivateSubnetA:
    Type: String
    Description: SubnetId in AZ A

  PrivateSubnetB:
    Type: String
    Description: SubnetId in AZ B

  PrivateSubnetC:
    Type: String
    Description: SubnetId in AZ C

  PublicSubnetA:
    Type: String
    Description: Public SubnetId in AZ A

  PublicSubnetB:
    Type: String
    Description: Public SubnetId in AZ B

  PublicSubnetC:
    Type: String
    Description: Public SubnetId in AZ C

  InternetGateway:
    Type: String
    Default: "-"

Resources:
  ##### Security groups
  SecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      VpcId: !Ref VPCID
      GroupDescription: Common SG for application vpc
      GroupName: !Sub '${Name}-security-group'
      SecurityGroupEgress:
      - CidrIp: 0.0.0.0/0
        IpProtocol: -1
      Tags:
      - Key: Name
        Value: !Sub '${Name} Security Group'
      SecurityGroupIngress:
      - FromPort: 5432
        ToPort: 5432
        IpProtocol: "tcp"
        Description: "Allow connections to a PostgreSQL DB instance"
        CidrIp: 0.0.0.0/0

  SGEntrySelf:
    Type: AWS::EC2::SecurityGroupIngress
    Properties:
      GroupId: !Ref SecurityGroup
      Description: access from self
      SourceSecurityGroupId: !GetAtt SecurityGroup.GroupId
      IpProtocol: -1

  ########
  PrivateRouteTableA:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref VPCID
      Tags:
      - Key: Name
        Value: !Sub '${Name}-private-route-table-a'

  PrivateRouteTableB:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref VPCID
      Tags:
      - Key: Name
        Value: !Sub '${Name}-private-route-table-b'

  PrivateRouteTableC:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref VPCID
      Tags:
       - Key: Name
         Value: !Sub '${Name}-private-route-table-c'

  PublicRouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref VPCID
      Tags:
       - Key: Name
         Value: !Sub '${Name}-public-route-table'

  ############## ASSOCIATIONS  ##############
  #ASSOCIATE PRIVATE ROUTE TABLE WITH PRIVATE SUBNETS
  PrivateSubnetARouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref PrivateSubnetA
      RouteTableId: !Ref PrivateRouteTableA

  PrivateSubnetBRouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref PrivateSubnetB
      RouteTableId: !Ref PrivateRouteTableB

  PrivateSubnetCRouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref PrivateSubnetC
      RouteTableId: !Ref PrivateRouteTableC

  #ASSOCIATE PUBLIC ROUTE TABLE WITH PUBLIC SUBNETS
  PublicSubnetARouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref PublicSubnetA
      RouteTableId: !Ref PublicRouteTable

  PublicSubnetBRouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref PublicSubnetB
      RouteTableId: !Ref PublicRouteTable

  PublicSubnetCRouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref PublicSubnetC
      RouteTableId: !Ref PublicRouteTable

  SSMSecurityGroup:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Sub "/config/infra/${Name}/security-group"
      Tier: "Standard"
      Type: "String"
      Value: !Ref SecurityGroup

Outputs:
  PublicRouteTable:
    Value: !Ref PublicRouteTable
    Description: Public Route Table for public subnets

  PrivateRouteTableA:
    Value: !Ref PrivateRouteTableA
    Description: Public Route Table for private subnets A

  PrivateRouteTableB:
    Value: !Ref PrivateRouteTableB
    Description: Public Route Table for private subnets B

  PrivateRouteTableC:
    Value: !Ref PrivateRouteTableC
    Description: Public Route Table for private subnets C

  PrivateRouteTable:
    Value: !Join
      - ','
      - - !Ref PrivateRouteTableA
        - !Ref PrivateRouteTableB
        - !Ref PrivateRouteTableC

  SG:
    Description: A reference to the security group
    Value: !Ref SecurityGroup
  SGID:
    Description: Id Sg
    Value: !GetAtt SecurityGroup.GroupId