Parameters:

  Name:
    Type: String
    Description: An environment name that will be prefixed to resource names

  VPCID:
    Type: AWS::EC2::VPC::Id
    Description: Choose which VPC the security groups should be deployed to

  PublicSubnetA:
    Type: String
    Description: Public SubnetId in AZ A

  PublicSubnetB:
    Type: String
    Description: Public SubnetId in AZ B

  PublicSubnetC:
    Type: String
    Description: Public SubnetId in AZ C

Resources:
  InternetGateway:
    Type: AWS::EC2::InternetGateway
    Properties:
      Tags:
        - Key: Name
          Value: !Sub ${Name}-ig

  InternetGatewayAttachment:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      InternetGatewayId: !Ref InternetGateway
      VpcId: !Ref VPCID

Outputs:
  InternetGateway:
    Value: !Ref InternetGateway
