AWSTemplateFormatVersion: 2010-09-09
Description: Merchant Platform Instance Postgres Database
Parameters:
  Environment:
    Description: Specify the Environment type of the stack.
    Type: String
    Default: dev
    AllowedValues:
      - dev
      - qa
      - staging
      - prod
  Name:
    Type: String
  Project:
    Type: String
  PublicSubnets:
    Description: Specify the Private subnets DB
    Type: String
  SGID:
    Type: String
  VPCData:
    Type: AWS::EC2::VPC::Id

  DBUsername:
    NoEcho: 'true'
    Description: Username for Postgresql database access
    Type: String
    MinLength: '1'
    MaxLength: '16'
    AllowedPattern: '[a-zA-Z][a-zA-Z0-9]*'
    ConstraintDescription: Must begin with a letter and contain only alphanumeric characters
    Default: postgres
  DBName:
    Type: String
    Default: mydata
  DBPort:
    Type: String
    Default: '5432'
Mappings:
  EnvAttrs:
    DBClassType:
      dev: db.t3.micro
      qa: db.t3.small
      staging: db.t3.small
      prod: db.t3.small
Resources:
  DBPassword:
    Type: 'AWS::SecretsManager::Secret'
    Properties:
      Description: !Join
        - ''
        - - 'Generated by the CDK for stack: '
          - !Ref 'AWS::StackName'
      GenerateSecretString:
        ExcludeCharacters: ' %+~`#$&*()|[]{}:;<>?!''/@"\=^,'
        GenerateStringKey: password
        PasswordLength: 30
        SecretStringTemplate: !Sub '{"username":"${DBUsername}"}'
  DBSubnetGroup:
    Type: 'AWS::RDS::DBSubnetGroup'
    Properties:
      DBSubnetGroupDescription: Subnet Group for postgres database
      DBSubnetGroupName: !Join
        - '-'
        - - !Ref Name
          - subnetgroup
      SubnetIds: !Split
        - ','
        - !Ref PublicSubnets
  DBInstance:
    Type: 'AWS::RDS::DBInstance'
    Properties:
      StorageEncrypted: true
      DBInstanceIdentifier: !Join
        - '-'
        - - !Ref Name
          - dbinstance
      DBSubnetGroupName: !Ref DBSubnetGroup
      VPCSecurityGroups:
        - !Ref SGID
      AllocatedStorage: '5'
      DBInstanceClass: !FindInMap
        - EnvAttrs
        - DBClassType
        - !Ref Environment
      Engine: postgres
      MasterUsername: !Ref DBUsername
      MasterUserPassword: !Join
        - ''
        - - '{{resolve:secretsmanager:'
          - !Ref DBPassword
          - ':SecretString:password::}}'
      Tags:
        - Key: Name
          Value: !Join
            - '-'
            - - !Ref Name
              - rds
      EnableCloudwatchLogsExports:
        - postgresql
      BackupRetentionPeriod: 35
    DeletionPolicy: Snapshot
    UpdateReplacePolicy: Snapshot
  SSMDbConfig:
    Type: 'AWS::SSM::Parameter'
    Properties:
      DataType: text
      Name: !Sub "/config/infra/${Environment}/${Project}/db/credentials"
      Tier: Standard
      Type: String
      Value: !Sub
        - |-
          {
            "db-name": "${DBName}",
            "db-user": "${DBUsername}",
            "db-password": "${DBPassword}",
            "db-host": "${DBHost}",
            "db-port": "${DBPort}"
          }
        - DBHost: !GetAtt
            - DBInstance
            - Endpoint.Address

Outputs:
  DBEndpoint:
    Description: Connection endpoint for the database
    Value: !GetAtt
      - DBInstance
      - Endpoint.Address
