AWSTemplateFormatVersion: 2010-09-09
Description: JSON string
Parameters:
  VpcCidr:
    Type: String
    Default: 10.192.0.0/16
  CidrPrivateSubnetA:
    Type: String
    Default: 10.192.10.0/24
  CidrPrivateSubnetB:
    Type: String
    Default: 10.192.20.0/24
  CidrPrivateSubnetC:
    Type: String
    Default: 10.192.30.0/24
  CidrPublicSubnetA:
    Type: String
    Default: 10.192.40.0/24
  CidrPublicSubnetB:
    Type: String
    Default: 10.192.50.0/24
  CidrPublicSubnetC:
    Type: String
    Default: 10.192.60.0/24
  Project:
    Type: String
    Default: "project"

  VpcCidr2:
    Type: String
    Default: 12.192.0.0/16
  CidrPrivateSubnetA2:
    Type: String
    Default: 12.192.10.0/24
  CidrPrivateSubnetB2:
    Type: String
    Default: 12.192.20.0/24
  CidrPrivateSubnetC2:
    Type: String
    Default: 12.192.30.0/24
  CidrPublicSubnetA2:
    Type: String
    Default: 12.192.40.0/24
  CidrPublicSubnetB2:
    Type: String
    Default: 12.192.50.0/24
  CidrPublicSubnetC2:
    Type: String
    Default: 12.192.60.0/24

Resources:
  SSMVpcCidr:
    Type: 'AWS::SSM::Parameter'
    Properties:
      Name: !Sub '/config/infra/${Project}/vpc-mydata/cidr'
      Tier: Standard
      Type: String
      Value: !Ref VpcCidr
  SSMCidrPrivateSubnetA:
    Type: 'AWS::SSM::Parameter'
    Properties:
      Name: !Sub '/config/infra/${Project}/vpc-mydata/cidr-private-subnet-a'
      Tier: Standard
      Type: String
      Value: !Ref CidrPrivateSubnetA
  SSMCidrPrivateSubnetB:
    Type: 'AWS::SSM::Parameter'
    Properties:
      Name: !Sub '/config/infra/${Project}/vpc-mydata/cidr-private-subnet-b'
      Tier: Standard
      Type: String
      Value: !Ref CidrPrivateSubnetB
  SSMCidrPrivateSubnetC:
    Type: 'AWS::SSM::Parameter'
    Properties:
      Name: !Sub '/config/infra/${Project}/vpc-mydata/cidr-private-subnet-c'
      Tier: Standard
      Type: String
      Value: !Ref CidrPrivateSubnetC
  SSMCidrPublicSubnetA:
    Type: 'AWS::SSM::Parameter'
    Properties:
      Name: !Sub '/config/infra/${Project}/vpc-mydata/cidr-public-subnet-a'
      Tier: Standard
      Type: String
      Value: !Ref CidrPublicSubnetA
  SSMCidrPublicSubnetB:
    Type: 'AWS::SSM::Parameter'
    Properties:
      Name: !Sub '/config/infra/${Project}/vpc-mydata/cidr-public-subnet-b'
      Tier: Standard
      Type: String
      Value: !Ref CidrPublicSubnetB
  SSMCidrPublicSubnetC:
    Type: 'AWS::SSM::Parameter'
    Properties:
      Name: !Sub '/config/infra/${Project}/vpc-mydata/cidr-public-subnet-c'
      Tier: Standard
      Type: String
      Value: !Ref CidrPublicSubnetC


  SSMVpcCidr2:
    Type: 'AWS::SSM::Parameter'
    Properties:
      Name: !Sub '/config/infra/${Project}/vpc-mydata2/cidr'
      Tier: Standard
      Type: String
      Value: !Ref VpcCidr2
  SSMCidrPrivateSubnetA2:
    Type: 'AWS::SSM::Parameter'
    Properties:
      Name: !Sub '/config/infra/${Project}/vpc-mydata2/cidr-private-subnet-a'
      Tier: Standard
      Type: String
      Value: !Ref CidrPrivateSubnetA2
  SSMCidrPrivateSubnetB2:
    Type: 'AWS::SSM::Parameter'
    Properties:
      Name: !Sub '/config/infra/${Project}/vpc-mydata2/cidr-private-subnet-b'
      Tier: Standard
      Type: String
      Value: !Ref CidrPrivateSubnetB2
  SSMCidrPrivateSubnetC2:
    Type: 'AWS::SSM::Parameter'
    Properties:
      Name: !Sub '/config/infra/${Project}/vpc-mydata2/cidr-private-subnet-c'
      Tier: Standard
      Type: String
      Value: !Ref CidrPrivateSubnetC2
  SSMCidrPublicSubnetA2:
    Type: 'AWS::SSM::Parameter'
    Properties:
      Name: !Sub '/config/infra/${Project}/vpc-mydata2/cidr-public-subnet-a'
      Tier: Standard
      Type: String
      Value: !Ref CidrPublicSubnetA2
  SSMCidrPublicSubnetB2:
    Type: 'AWS::SSM::Parameter'
    Properties:
      Name: !Sub '/config/infra/${Project}/vpc-mydata2/cidr-public-subnet-b'
      Tier: Standard
      Type: String
      Value: !Ref CidrPublicSubnetB2
  SSMCidrPublicSubnetC2:
    Type: 'AWS::SSM::Parameter'
    Properties:
      Name: !Sub '/config/infra/${Project}/vpc-mydata2/cidr-public-subnet-c'
      Tier: Standard
      Type: String
      Value: !Ref CidrPublicSubnetC2
